version: '2'

services:
  hub:
    image: elgalu/selenium
    ports:
      - ${SELENIUM_HUB_PORT}:${SELENIUM_HUB_PORT}
      # We need a fixed port range to expose VNC
      # due to a bug in Docker for Mac beta (1.12)
      # https://forums.docker.com/t/docker-for-mac-beta-not-forwarding-ports/8658/6
      - ${VNC_FROM_PORT}-${VNC_TO_PORT}:${VNC_FROM_PORT}-${VNC_TO_PORT}
      # e.g. (hard-coded)
      # - 40650-40700:40650-40700
    environment:
      - SELENIUM_HUB_PORT
      - PICK_ALL_RANDMON_PORTS=true
      - GRID=true
      - CHROME=false
      - FIREFOX=false

  chrome:
    image: elgalu/selenium
    network_mode: "service:hub"
    shm_size: 1g
    mem_limit: 2g
    memswap_limit: 4g
    # 90000 means 90%
    # cpu_quota: 90000
    environment:
      - SELENIUM_HUB_PORT
      - VNC_FROM_PORT
      - VNC_TO_PORT
      - SCREEN_WIDTH=1300
      - SCREEN_HEIGHT=999
      - PICK_ALL_RANDMON_PORTS=true
      - VIDEO
      - GRID=false
      - CHROME=true
      - FIREFOX=false

  firefox:
    image: elgalu/selenium
    network_mode: "service:hub"
    mem_limit: 2g
    memswap_limit: 4g
    # 90000 means 90%
    # cpu_quota: 90000
    environment:
      - SELENIUM_HUB_PORT
      - VNC_FROM_PORT
      - VNC_TO_PORT
      - SCREEN_WIDTH=1300
      - SCREEN_HEIGHT=999
      - PICK_ALL_RANDMON_PORTS=true
      - VIDEO
      - GRID=false
      - CHROME=false
      - FIREFOX=true

  mock:
    image: elgalu/google_adwords_mock
    network_mode: "service:hub"
    tty: true
    environment:
      - MOCK_SERVER_PORT=8080

  # zalando_uk:
  #   image: elgalu/uk_mock
  #   network_mode: "service:hub"
  #   tty: true
  #   environment:
  #     - MOCK_SERVER_PORT=8080

#-- Notes --#
# shm_size: 1g
#  Fixes small 64 mb /dev/shm inside docker containers
#   see: https://github.com/docker/compose/blob/1.7.1/compose/config/config.py#L79
#  Can also be fixed with:
#   volumes:
#     - /dev/shm:/dev/shm
#  Can also be fixed with:
#   environment:
#     - SHM_TRY_MOUNT_UNMOUNT=true
